package com.socialmediaapp.exceptions;

public enum EntityType {
    ADMIN_USER,COUNTRY,INDUSTRY,ORGANIZATION,PACKAGE,SUBSCRIPTION,ROLE,ORGANIZATION_USER
    ,SQUAD,TECHSTACK,ENGINEER,ENGINEER_ASSIGNMENT,ENGINEER_REPORT,ENGINEER_ASSIGNMENT_COMMENT,
    USER, ENGINEER_ASSIGNMENT_REQUEST, SUBSCRIPTION_REQUEST,INVOICE, BILLING_RATE, PROFILE_VIEW_REQUEST_NOTIFICATION
    , ENGINEER_ASSIGNMENT_REQUEST_LINE_ITEM,STATE,BATCH,TRAINING_DATA_POINT,FRAMEWORK, ENGINEER_PLACEMENT_REQUEST, ENGINEER_PLACEMENT_REQUEST_LINE_ITEM
}
